discord-jar/discord.jar

.github/workflows/codeql-analysis.yml

Updated CodeQL config for Java 17

Updated CodeQL config for Java 17

---

pom.xml

package updated java ver

---

src/main/java/com/seailz/javadiscordwrapper/model/component/ComponentType.java
src/main/java/com/seailz/javadiscordwrapper/model/component/button/Button.java
src/main/java/com/seailz/javadiscordwrapper/model/component/button/internal/ButtonImpl.java

moved buttonImpl to an internal package

---

src/main/java/com/seailz/javadiscordwrapper/DiscordJv.java
src/main/java/com/seailz/javadiscordwrapper/action/interaction/InteractionCallbackAction.java
src/main/java/com/seailz/javadiscordwrapper/action/interaction/MessageInteractionCallbackAction.java
src/main/java/com/seailz/javadiscordwrapper/action/interaction/ModalInteractionCallbackAction.java
src/main/java/com/seailz/javadiscordwrapper/events/DiscordListener.java
src/main/java/com/seailz/javadiscordwrapper/events/EventDispatcher.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/InteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/button/ButtonInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/modal/ModalInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/select/StringSelectMenuInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/select/entity/ChannelSelectMenuInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/select/entity/RoleSelectMenuInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/select/entity/UserSelectMenuInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/gateway/events/DispatchedEvents.java
src/main/java/com/seailz/javadiscordwrapper/gateway/heartbeat/HeartbeatCycle.java
src/main/java/com/seailz/javadiscordwrapper/model/component/ActionComponent.java
src/main/java/com/seailz/javadiscordwrapper/model/component/Component.java
src/main/java/com/seailz/javadiscordwrapper/model/component/ComponentType.java
src/main/java/com/seailz/javadiscordwrapper/model/component/DisplayComponent.java
src/main/java/com/seailz/javadiscordwrapper/model/component/MessageComponent.java
src/main/java/com/seailz/javadiscordwrapper/model/component/ModalComponent.java
src/main/java/com/seailz/javadiscordwrapper/model/component/modal/ResolvedModalComponent.java
src/main/java/com/seailz/javadiscordwrapper/model/component/text/TextInput.java
src/main/java/com/seailz/javadiscordwrapper/model/component/text/TextInputStyle.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/data/modal/ModalSubmitInteractionData.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/modal/Modal.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/reply/InteractionModalResponse.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/reply/InteractionReply.java

Closes Issue: #2 
Added modals

[FEATURE] Added Modals and Text Inputs

---

src/main/java/com/seailz/javadiscordwrapper/DiscordJv.java
src/main/java/com/seailz/javadiscordwrapper/events/model/general/ReadyEvent.java
src/main/java/com/seailz/javadiscordwrapper/events/model/interaction/command/CommandInteractionEvent.java
src/main/java/com/seailz/javadiscordwrapper/model/application/Application.java
src/main/java/com/seailz/javadiscordwrapper/model/channel/GroupDM.java
src/main/java/com/seailz/javadiscordwrapper/model/component/button/internal/ButtonImpl.java
src/main/java/com/seailz/javadiscordwrapper/model/component/select/SelectOption.java
src/main/java/com/seailz/javadiscordwrapper/model/component/select/string/StringSelectMenu.java
src/main/java/com/seailz/javadiscordwrapper/model/emoji/Emoji.java
src/main/java/com/seailz/javadiscordwrapper/model/emoji/Reaction.java
src/main/java/com/seailz/javadiscordwrapper/model/emoji/sticker/Sticker.java
src/main/java/com/seailz/javadiscordwrapper/model/guild/Guild.java
src/main/java/com/seailz/javadiscordwrapper/model/guild/Member.java
src/main/java/com/seailz/javadiscordwrapper/model/guild/UnavailableGuild.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/Interaction.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/InteractionData.java
src/main/java/com/seailz/javadiscordwrapper/model/interaction/data/message/MessageComponentInteractionData.java
src/main/java/com/seailz/javadiscordwrapper/model/message/Message.java
src/main/java/com/seailz/javadiscordwrapper/model/status/Status.java
src/main/java/com/seailz/javadiscordwrapper/model/status/activity/Activity.java
src/main/java/com/seailz/javadiscordwrapper/model/team/Team.java
src/main/java/com/seailz/javadiscordwrapper/model/team/member/TeamMember.java
src/main/java/com/seailz/javadiscordwrapper/model/user/User.java
src/main/java/com/seailz/javadiscordwrapper/utils/URLS.java
src/main/java/com/seailz/javadiscordwrapper/utils/cache/Cache.java
src/main/java/com/seailz/javadiscordwrapper/utils/discordapi/DiscordResponse.java

User Methods

---

src/main/java/com/seailz/javadiscordwrapper/DiscordJv.java
src/main/java/com/seailz/javadiscordwrapper/gateway/GatewayFactory.java
src/main/java/com/seailz/javadiscordwrapper/utils/URLS.java
src/main/java/com/seailz/javadiscordwrapper/utils/discordapi/DiscordRequest.java
src/main/java/com/seailz/javadiscordwrapper/utils/version/APIVersion.java
src/main/java/com/seailz/javadiscordwrapper/utils/version/APIVersionState.java

feat: added custom api verrsion picker

fix: added some more error handling & api version customization

---

src/main/java/com/seailz/javadiscordwrapper/DiscordJv.java
src/main/java/com/seailz/javadiscordwrapper/utils/Checker.java

feat: added Checker.java class for checking args

---

README.md

updating feature/verifiedroleconnections

---

pom.xml
src/main/java/com/seailz/discordjv/events/model/interaction/InteractionEvent.java
src/main/java/com/seailz/discordjv/events/model/message/MessageCreateEvent.java
src/main/java/com/seailz/discordjv/model/interaction/Interaction.java
src/main/java/com/seailz/discordjv/utils/Checker.java
src/main/java/com/seailz/discordjv/utils/annotation/UtilityClass.java
token.txt

Removes Lombok from the project

[FEATURE] Removed need for Lombok

---

.github/FUNDING.yml
src/main/java/com/seailz/javadiscordwrapper/DiscordJv.java
src/main/java/com/seailz/javadiscordwrapper/model/application/Application.java
src/main/java/com/seailz/javadiscordwrapper/model/commands/Command.java
src/main/java/com/seailz/javadiscordwrapper/model/commands/CommandChoice.java
src/main/java/com/seailz/javadiscordwrapper/model/commands/CommandOption.java
src/main/java/com/seailz/javadiscordwrapper/model/commands/CommandType.java
src/main/java/com/seailz/javadiscordwrapper/model/guild/Guild.java
src/main/java/com/seailz/javadiscordwrapper/utils/Checker.java
src/main/java/com/seailz/javadiscordwrapper/utils/URLS.java
src/main/java/com/seailz/javadiscordwrapper/utils/discordapi/DiscordRequest.java

Frontend command creation implementation

[FEATURE] Frontend Command Creation Implementation

---

pom.xml
src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/action/sticker/ModifyStickerAction.java
src/main/java/com/seailz/discordjv/command/CommandDispatcher.java
src/main/java/com/seailz/discordjv/command/annotation/CommandInfo.java
src/main/java/com/seailz/discordjv/command/listeners/CommandListener.java
src/main/java/com/seailz/discordjv/command/listeners/MessageContextCommandListener.java
src/main/java/com/seailz/discordjv/command/listeners/SlashCommandListener.java
src/main/java/com/seailz/discordjv/command/listeners/UserContextCommandListener.java
src/main/java/com/seailz/discordjv/events/model/interaction/command/CommandInteractionEvent.java
src/main/java/com/seailz/discordjv/events/model/interaction/command/MessageContextCommandInteractionEvent.java
src/main/java/com/seailz/discordjv/events/model/interaction/command/SlashCommandInteractionEvent.java
src/main/java/com/seailz/discordjv/events/model/interaction/command/UserContextCommandInteractionEvent.java
src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
src/main/java/com/seailz/discordjv/gateway/events/DispatchedEvents.java
src/main/java/com/seailz/discordjv/gateway/heartbeat/HeartbeatCycle.java
src/main/java/com/seailz/discordjv/model/commands/Command.java
src/main/java/com/seailz/discordjv/model/commands/CommandChoice.java
src/main/java/com/seailz/discordjv/model/commands/CommandOption.java
src/main/java/com/seailz/discordjv/model/commands/CommandType.java
src/main/java/com/seailz/discordjv/model/guild/GuildFeature.java
src/main/java/com/seailz/discordjv/model/interaction/data/command/ApplicationCommandInteractionData.java
src/main/java/com/seailz/discordjv/utils/Checker.java
src/main/java/com/seailz/discordjv/utils/URLS.java
src/main/java/com/seailz/discordjv/utils/annotation/UtilityClass.java
src/main/java/com/seailz/discordjv/utils/cache/Cache.java
src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

Closes #44 
Adds the frontend implementation of commands described in #44

[FEATURE] Command Frontend

---

src/main/java/com/seailz/discordjv/action/MessageCreateAction.java
src/main/java/com/seailz/discordjv/action/sticker/ModifyStickerAction.java

feat: added completable futures

---

src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/action/automod/AutomodRuleCreateAction.java
src/main/java/com/seailz/discordjv/action/automod/AutomodRuleModifyAction.java
src/main/java/com/seailz/discordjv/model/automod/AutomodRule.java
src/main/java/com/seailz/discordjv/model/guild/Guild.java
src/main/java/com/seailz/discordjv/utils/URLS.java

[FEATURE] Automod

---

examples/pom.xml
examples/src/main/java/com/seailz/djv/examples/Bot.java
examples/src/main/java/com/seailz/djv/examples/ExampleCommand.java
examples/src/main/java/com/seailz/djv/examples/ExampleMessageCommand.java
pom.xml

[EXAMPLES] Added examples

---

src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
src/main/java/com/seailz/discordjv/utils/cache/Cache.java

Closes #53 
Cache guilds when retrieved from the API

[CACHE] Cache guilds when retrieved from the API

---

pom.xml
src/main/java/com/seailz/discordjv/DiscordJv.java

fic: attempted to fix pom.xml

---

src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

Closes #0
updates the user agent for http requests

feat: update the user agent a little

---

src/main/java/com/seailz/discordjv/command/CommandDispatcher.java

Closes #66 
Fixed commands getting dispatched twice

[FIX] Commands getting dispatched twice

---

src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/action/guild/GetCurrentUserGuildsAction.java
src/main/java/com/seailz/discordjv/utils/URLS.java
src/main/java/com/seailz/discordjv/utils/cache/Cache.java

Closes #26 
Added the get current user guilds endpoint and made some changes to the cache for easier caching of things.

feat: added Get Current User Guilds endpoint

---

src/main/java/com/seailz/discordjv/action/interaction/InteractionCallbackAction.java
src/main/java/com/seailz/discordjv/action/interaction/followup/InteractionFollowupAction.java
src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java
src/main/java/com/seailz/discordjv/model/interaction/callback/internal/InteractionHandlerImpl.java
src/main/java/com/seailz/discordjv/model/interaction/reply/InteractionMessageResponse.java
src/main/java/com/seailz/discordjv/utils/URLS.java

Closes #57 
Added follow ups for interactions.

[FEATURE] Interaction Followups

---

src/main/java/com/seailz/discordjv/model/user/UserFlag.java

Closes #71 
Awaiting https://github.com/discord/discord-api-docs/pull/5695
`UserFlag.DISCORD_CERTIFIED_MODERATOR` -> `UserFlag.CERTIFIED_MODERATOR_ALUMNI`

[DOC] Changed documentation regarding certified moderator flag

---

src/main/java/com/seailz/discordjv/DiscordJv.java

Addresses #78 
First item of #78 (remove redundant CRLF check)

[Feature Request] Remove \\r\\n check on token during initialization of discord.jv

---

src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
src/main/java/com/seailz/discordjv/model/guild/Guild.java
src/main/java/com/seailz/discordjv/model/guild/Member.java
src/main/java/com/seailz/discordjv/utils/cache/JsonCache.java
src/main/java/com/seailz/discordjv/utils/cache/impl/JsonCacheImpl.java
src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

Closes #0
Added a new `JsonCache` object and added caching to `DiscordJv#getSelfInfo`

[CACHE] Added new `JsonCache` object and added caching to getSelfInfo

---

src/main/java/com/seailz/discordjv/command/permissions/ApplicationCommandPermissions.java
src/main/java/com/seailz/discordjv/command/permissions/ApplicationCommandPermissionsData.java
src/main/java/com/seailz/discordjv/model/application/Application.java
src/main/java/com/seailz/discordjv/model/automod/AutomodRule.java
src/main/java/com/seailz/discordjv/model/channel/Channel.java
src/main/java/com/seailz/discordjv/model/channel/audio/VoiceRegion.java
src/main/java/com/seailz/discordjv/model/channel/forum/ForumTag.java
src/main/java/com/seailz/discordjv/model/emoji/Emoji.java
src/main/java/com/seailz/discordjv/model/emoji/sticker/Sticker.java
src/main/java/com/seailz/discordjv/model/emoji/sticker/StickerPack.java
src/main/java/com/seailz/discordjv/model/guild/Guild.java
src/main/java/com/seailz/discordjv/model/guild/UnavailableGuild.java
src/main/java/com/seailz/discordjv/model/interaction/data/command/ApplicationCommandInteractionData.java
src/main/java/com/seailz/discordjv/model/message/Attachment.java
src/main/java/com/seailz/discordjv/model/message/Message.java
src/main/java/com/seailz/discordjv/model/permission/PermissionOverwrite.java
src/main/java/com/seailz/discordjv/model/status/activity/ActivityParty.java
src/main/java/com/seailz/discordjv/model/team/Team.java
src/main/java/com/seailz/discordjv/utils/Snowflake.java

Closes #0
Added a snowflake class

Snowflake class

---

src/main/java/com/seailz/discordjv/model/guild/Guild.java
src/main/java/com/seailz/discordjv/model/user/User.java
src/main/java/com/seailz/discordjv/utils/CDNAble.java
src/main/java/com/seailz/discordjv/utils/StringFormatter.java

Closes #0
At the moment only avatar hashes are supported. This PR is a start to implementing CDN URLs as well as hashes.

Support Image URLs

---

src/main/java/com/seailz/discordjv/model/message/Message.java

Closes #0
Added a method that returns formatted text in a Message.

Formatted Message Content

---

pom.xml
src/main/java/com/seailz/discordjv/model/channel/MessagingChannel.java
src/main/java/com/seailz/discordjv/model/channel/transcript/TranscriptFormatter.java
src/main/java/com/seailz/discordjv/model/message/Message.java
src/main/java/com/seailz/discordjv/utils/URLS.java
src/main/resources/template.html

Closes #0
Added channel transcripts

Channel Transcripts

---

src/main/java/com/seailz/discordjv/action/MessageCreateAction.java
src/main/java/com/seailz/discordjv/model/channel/MessagingChannel.java
src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

File Uploads

---

src/main/java/com/seailz/discordjv/model/message/Attachment.java

fix testing

---

README.md
pom.xml
src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/command/CommandDispatcher.java
src/main/java/com/seailz/discordjv/http/HttpOnlyApplication.java
src/main/java/com/seailz/discordjv/http/HttpOnlyManager.java
src/main/java/com/seailz/discordjv/http/SecurityManager.java
src/main/java/com/seailz/discordjv/model/interaction/Interaction.java
src/main/java/com/seailz/discordjv/utils/HTTPOnlyInfo.java

Closes #0
Adds support for HTTP-only bots

[FEATURE] HTTP-Only Support

---

src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

Closes #0
Fixed uploading files

[FIX] Uploading Files

---

src/main/java/com/seailz/discordjv/events/model/interaction/InteractionEvent.java
src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java

Closes #0
Added some extra interaction methods

[FEATURE] Added some extra interaction methods

---

src/main/java/com/seailz/discordjv/action/interaction/EditInteractionMessageAction.java
src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java
src/main/java/com/seailz/discordjv/model/interaction/callback/internal/InteractionHandlerImpl.java
src/main/java/com/seailz/discordjv/utils/URLS.java

Closes #0
Implemented editing of interaction responses

[FEATURE] Interaction Messages Editing

---

src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java
src/main/java/com/seailz/discordjv/model/interaction/callback/internal/InteractionHandlerImpl.java

Closes #0
Added support for a type 6 interaction response - ACKs the interaction with the intention to edit later. No loading state is shown. This is only supported for component-based interactions.

[FEATURE] Type 6 interaction response

---

src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

Closes #109 
Updated the user agent to include a direct link to the repository & renamed to discord.jar.

[RENAME] Updated User Agent

---

src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

fix: testing

---

src/main/java/com/seailz/discordjv/model/guild/Member.java
src/main/java/com/seailz/discordjv/model/guild/MemberFlags.java

Closes #113 
Added Member flags and cleaned up the `Member` class slightly

[FEATURE] Guild Member Flags

---

src/main/java/com/seailz/discordjv/action/automod/AutomodRuleModifyAction.java
src/main/java/com/seailz/discordjv/model/guild/Guild.java

[FEATURE] Modify Automod Rule

---

src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/command/Command.java
src/main/java/com/seailz/discordjv/command/annotation/ContextCommandInfo.java
src/main/java/com/seailz/discordjv/command/annotation/Locale.java
src/main/java/com/seailz/discordjv/command/annotation/SlashCommandInfo.java

Closes #0
Added support for features such as name and description localization, nsfw commands, etc in the CommandInfo annotations.

[FEATURE] Command customization

---

src/main/java/com/seailz/discordjv/events/model/interaction/InteractionEvent.java
src/main/java/com/seailz/discordjv/events/model/interaction/button/ButtonInteractionEvent.java
src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
src/main/java/com/seailz/discordjv/model/channel/Category.java
src/main/java/com/seailz/discordjv/model/channel/MessagingChannel.java
src/main/java/com/seailz/discordjv/model/component/button/Button.java
src/main/java/com/seailz/discordjv/model/component/button/internal/ButtonImpl.java
src/main/java/com/seailz/discordjv/model/guild/Member.java
src/main/java/com/seailz/discordjv/utils/Registry.java
src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java
src/main/java/com/seailz/discordjv/utils/discordapi/RateLimit.java
src/main/java/com/seailz/discordjv/utils/flag/BitwiseUtil.java
src/main/java/com/seailz/discordjv/utils/registry/ButtonRegistry.java

Closes #120 
Button actions, needs testing.

[FEATURE] Button Actions

---

src/main/java/com/seailz/discordjv/action/channel/ModifyBaseChannelAction.java
src/main/java/com/seailz/discordjv/model/channel/ForumChannel.java
src/main/java/com/seailz/discordjv/model/channel/internal/ForumChannelImpl.java

Closes #69 
Adds the default_forum_layout property into discord.jar
Reference: https://github.com/discord/discord-api-docs/pull/5745

[FEATURE] Default Forum Layout forum channel property

---

src/main/java/com/seailz/discordjv/DiscordJv.java
src/main/java/com/seailz/discordjv/model/invite/Invite.java
src/main/java/com/seailz/discordjv/model/invite/internal/InviteImpl.java
src/main/java/com/seailz/discordjv/utils/URLS.java
src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java

Closes #23 
Adds support for invites.

[FEATURE] Invites

---

src/main/java/com/seailz/discordjv/model/status/Status.java

Closes #0
Added simpler creation of the Status object.

[FEATURE] Simpler creation of Status object

---

src/main/java/com/seailz/discordjar/model/message/MessageFlag.java

Closes #128 
Added support for “silent” messages.

[FEATURE] Silent Messages

---

src/main/java/com/seailz/discordjar/model/message/MessageType.java

Closes #131 
Added new message types relating to stages and role subscriptions.

[FEATURE] New Message Types

---

src/main/java/com/seailz/discordjar/events/model/automod/AutoModExecutionEvent.java
src/main/java/com/seailz/discordjar/events/model/automod/rule/AutoModRuleCreateEvent.java
src/main/java/com/seailz/discordjar/events/model/automod/rule/AutoModRuleDeleteEvent.java
src/main/java/com/seailz/discordjar/events/model/automod/rule/AutoModRuleEvent.java
src/main/java/com/seailz/discordjar/events/model/automod/rule/AutoModRuleUpdateEvent.java
src/main/java/com/seailz/discordjar/events/model/guild/GuildEvent.java
src/main/java/com/seailz/discordjar/gateway/events/DispatchedEvents.java
src/main/java/com/seailz/discordjar/model/channel/Channel.java

[FEATURE] AutoMod gateway events

---

src/main/java/com/seailz/discordjar/gateway/GatewayFactory.java

Closes #137 
A couple gateway bug fixes.

[BUG] A couple gateway bug fixes.

---

src/main/java/com/seailz/discordjar/action/message/MessageEditAction.java
src/main/java/com/seailz/discordjar/model/message/Message.java
src/main/java/com/seailz/discordjar/utils/URLS.java

Closes #0
Adds the ability to edit a message

[FEATURE] Message Editing

---

src/main/java/com/seailz/discordjar/model/guild/Guild.java
src/main/java/com/seailz/discordjar/utils/URLS.java

Closes #135 
Added support for guild onboarding
https://github.com/discord/discord-api-docs/pull/5915

[FEATURE] Guild Onboarding Support

---

src/main/java/com/seailz/discordjar/model/guild/Guild.java

Closes #151 
Added support for the `max_stage_video_channel_users` property

[FEATURE] Added support for `max_stage_video_channel_users` property

---

src/main/java/com/seailz/discordjar/cache/Cache.java

fix: Fixed ConcurrentModifiedException in Cache.java

---

src/main/java/com/seailz/discordjar/model/interaction/Interaction.java

Closes #156 
Added support for the `channel` field in interactions
Reference: https://github.com/discord/discord-api-docs/pull/6051

[FEATURE] Added support for `channel` field in interactions

---

src/main/java/com/seailz/discordjar/DiscordJar.java
src/main/java/com/seailz/discordjar/DiscordJarBuilder.java
src/main/java/com/seailz/discordjar/cache/Cache.java
src/main/java/com/seailz/discordjar/gateway/events/DispatchedEvents.java
src/main/java/com/seailz/discordjar/model/guild/Guild.java

…DiscordJarBuilder class to be completed in a future PR, and added member caching.
Closes #0

[FEATURE] Member Caching

---

README.md
src/main/java/com/seailz/discordjar/DiscordJar.java
src/main/java/com/seailz/discordjar/DiscordJarBuilder.java

Closes #168 
Deprecates the constructors in the DiscordJar class and adds a new DiscordJarBuilder class that is recommended to be used instead.

feat(builder): Added a builder class to discord.jar

---

src/main/java/com/seailz/discordjar/action/message/MessageCreateAction.java
src/main/java/com/seailz/discordjar/action/message/MessageEditAction.java
src/main/java/com/seailz/discordjar/model/message/Message.java
src/main/java/com/seailz/discordjar/model/message/MessageFlag.java
src/main/java/com/seailz/discordjar/utils/permission/Permission.java

Closes #161 
adds voice messages

feat(messages, permissions): added necessary additions for voice messages

---

src/main/java/com/seailz/discordjar/DiscordJar.java
src/main/java/com/seailz/discordjar/DiscordJarBuilder.java
src/main/java/com/seailz/discordjar/model/api/APIRelease.java
src/main/java/com/seailz/discordjar/model/api/version/APIVersion.java
src/main/java/com/seailz/discordjar/model/api/version/APIVersionState.java
src/main/java/com/seailz/discordjar/utils/HTTPOnlyInfo.java
src/main/java/com/seailz/discordjar/utils/URLS.java

Closes #0
Implemented support for customizing the API release (stable, canary, ptb)

feat(urls): implemented api release customization

---

src/main/java/com/seailz/discordjar/model/channel/interfaces/Transcriptable.java

feat(transcripts): implemented a feature that returns all attachments

---

src/main/java/com/seailz/discordjar/utils/permission/Permission.java

Closes #176 
Implements the permission documented in https://github.com/discord/discord-api-docs/pull/6039

feat(perms): added use external sounds permission (45)

---

src/main/java/com/seailz/discordjar/model/user/User.java
src/main/java/com/seailz/discordjar/utils/URLS.java

Closes #0
added necessary changes for pomelo
(please cancel this update, discord).

feat(usernames): pomelo (new username system)

---

src/main/java/com/seailz/discordjar/DiscordJar.java
src/main/java/com/seailz/discordjar/cache/Cache.java
src/main/java/com/seailz/discordjar/events/model/general/ReadyEvent.java
src/main/java/com/seailz/discordjar/gateway/events/DispatchedEvents.java
src/main/java/com/seailz/discordjar/model/guild/Guild.java

feat(caching): implemented member caching

---

src/main/java/com/seailz/discordjar/events/DiscordListener.java
src/main/java/com/seailz/discordjar/events/model/channel/ChannelEvent.java
src/main/java/com/seailz/discordjar/events/model/channel/ChannelPinsUpdateEvent.java
src/main/java/com/seailz/discordjar/events/model/channel/edit/ChannelCreateEvent.java
src/main/java/com/seailz/discordjar/events/model/channel/edit/ChannelDeleteEvent.java
src/main/java/com/seailz/discordjar/events/model/channel/edit/ChannelUpdateEvent.java
src/main/java/com/seailz/discordjar/events/model/guild/GuildDeleteEvent.java
src/main/java/com/seailz/discordjar/events/model/guild/GuildUpdateEvent.java
src/main/java/com/seailz/discordjar/events/model/message/TypingStartEvent.java
src/main/java/com/seailz/discordjar/gateway/events/DispatchedEvents.java

Contributes to #30 
implemented more gateway events

feat(events): implemented more gateway events

---

src/main/java/com/seailz/discordjar/model/role/Role.java

Closes #196 
Implemented support for role flags

feat(roles): role flags

---

src/main/java/com/seailz/discordjar/model/user/User.java
src/main/java/com/seailz/discordjar/utils/image/ImageUtils.java

Closes #200 
Added support for avatar decorations

feat(user): avatar decorations

---

src/main/java/com/seailz/discordjar/DiscordJar.java
src/main/java/com/seailz/discordjar/utils/rest/DiscordRequest.java
src/main/java/com/seailz/discordjar/utils/rest/ratelimit/Bucket.java

Closes #0
Fixed discord.jar's internal client-side rate-limiting handling implementation to no longer cause issues!!

Ratelimiting v2

---

src/main/java/com/seailz/discordjar/utils/rest/DiscordRequest.java

feat(unhandled-discord-api-exception): print stack trace

---

pom.xml
src/main/java/com/seailz/discordjar/action/guild/scheduledevents/CreateScheduledEventAction.java
src/main/java/com/seailz/discordjar/action/guild/scheduledevents/ModifyScheduledEventAction.java
src/main/java/com/seailz/discordjar/model/guild/Guild.java
src/main/java/com/seailz/discordjar/model/guild/scheduledevents/ScheduledEvent.java
src/main/java/com/seailz/discordjar/utils/URLS.java

Closes #61 
Implemented scheduled events

feat(guilds): implemented scheduled events

---

pom.xml

bumped project to b-1.1

---

src/main/java/com/seailz/discordjar/gateway/GatewayFactory.java

feat(gateway): removed use of gateway close code 1015

---

src/main/java/com/seailz/discordjar/events/EventDispatcher.java
src/main/java/com/seailz/discordjar/utils/thread/DiscordJarThreadAllocator.java

feat(threads): added a new util class that helps with allocating threads

---

src/main/java/com/seailz/discordjar/DiscordJar.java
src/main/java/com/seailz/discordjar/action/sku/ListEntitlementRequest.java
src/main/java/com/seailz/discordjar/model/monetization/Entitlement.java
src/main/java/com/seailz/discordjar/model/monetization/SKU.java
src/main/java/com/seailz/discordjar/utils/URLS.java
src/main/java/com/seailz/discordjar/utils/flag/BitwiseUtil.java
src/main/java/com/seailz/discordjar/utils/flag/Bitwiseable.java

Closes #238 
Implemented support for [the new premium apps system](https://discord.com/developers/docs/monetization/overview).
just usa devs atm :(

feat(monetization): implemented support for the new premium apps system

---

src/main/java/com/seailz/discordjar/model/component/select/AutoPopulatedSelect.java
src/main/java/com/seailz/discordjar/model/component/select/entity/ChannelSelectMenu.java
src/main/java/com/seailz/discordjar/model/component/select/entity/MentionableSelectMenu.java
src/main/java/com/seailz/discordjar/model/component/select/entity/MentionableType.java
src/main/java/com/seailz/discordjar/model/component/select/entity/RoleSelectMenu.java
src/main/java/com/seailz/discordjar/model/component/select/entity/UserSelectMenu.java

Closes #229 
added support for the new `default_values` field on auto populated select menus

Auto-populated Select Menu default_values field support

---

src/main/java/com/seailz/discordjar/model/interaction/InteractionData.java
src/main/java/com/seailz/discordjar/model/interaction/data/message/MessageComponentInteractionData.java

Closes #241 
added support for the `resolved` field in message component interactions

feat(interactions): added support for the `resolved` field in message component interactions

---

src/main/java/com/seailz/discordjar/model/guild/Guild.java

reversed previous change

---

src/main/java/com/seailz/discordjar/action/message/MessageCreateAction.java

Closes #268 
Add `enforce_nonce` to the payload + setter/getter.

feat(MessageCreateAction): add `enforceNonce` parameter

---

src/main/java/com/seailz/discordjar/events/EventDispatcher.java

Ensure listeners are of the structure `onEvent(Event e)` and nothing else.
Copy of #277

refactor(events): Validate listeners

---

src/main/java/com/seailz/discordjar/model/guild/Guild.java

Remove `throws IllegalAccessException` as it is not needed.

refactor(Guild): Drop IllegalAccessException

---

src/main/java/com/seailz/discordjar/model/guild/Guild.java

Return an empty un-modifiable list, avoiding an NPE.

refactor(model): Fix NPE in Guild#roles

---

src/main/java/com/seailz/discordjar/utils/rest/DiscordRequest.java

Remove unneeded null guard since the null guard at line 216 already sets the content type.

refactor(rest): Remove unneeded null guard

---

src/main/java/com/seailz/discordjar/command/Command.java

As per the documentation several of the application command fields types are possibly `null`. This is fixed with this PR.

fix(commands): Null check possibly null types in decompile
